name: SOMAR
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9.20
  - hdf5=*=*mpich*
  - h5py=*=mpi*
  - gxx_linux-64
  - paraview
  - ipython
  - colorama
variables:
  SOMAR_ROOT: <your-path-to-SOMAR>




